id: D1BD2B98D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:59:52+00:00'
last_modified: '2022-05-26T11:04:00.426010+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    cb22:
      image_group_id: I1PD95871
      title: ཚིགས་སུ་བཅད་པ་ཕྱེད་དང་ལྔ།
      total_pages: 1902
      order: 26
      base_file: cb22.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
