id: P68101A62
initial_creation_type: ocr
source_metadata:
  volumes:
    2bcd9be68f624cf7b017cbb51e6efae1:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཚིགས་སུ་བཅད་པ་ཕྱེད་དང་ལྔ།
      total_pages: 1902
      volume_number: 26
